version: '3.3'
services:
  db:
    image: postgres:14-alpine
    container_name: pgsql-db-1
    volumes:
      - /db_backup/:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - 5433:5432