// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Post struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	// Content of the post
	Body      string       `json:"body"`
	UserID    int64        `json:"user_id"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}
