// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Post struct {
	ID    int64          `json:"id"`
	Title sql.NullString `json:"title"`
	// Content of the post
	Body      sql.NullString `json:"body"`
	UserID    int64          `json:"user_id"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  sql.NullString `json:"username"`
	Role      sql.NullString `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
